---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: dev-ca-ss
  namespace: cert-manager
spec:
  selfSigned: {}
---
# Самоподписанный сертификат CA
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-ca
  namespace: cert-manager
spec:
  isCA: true
  duration: 87600h # 10y
  subject:
    organizations:
      - "Systemoteh dev"
    organizationalUnits:
      - "Systemoteh lab"
    localities:
      - "Moscow"
    countries:
      - "RU"
  commonName: "Systemoteh Ru CA"
  secretName: dev-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  issuerRef:
    name: dev-ca-ss
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dev-ca-issuer
spec:
  ca:
    secretName: dev-ca