apiVersion: v2
name: gitflic
description: A Gitflic Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "2.16.1"
maintainers:
  - name: systemoteh
    email: mail@systemoteh.ru
    url: https://www.systemoteh.ru
dependencies:
  - name: redis
    version: 18.5.0
    repository: https://mirror.yandex.ru/helm/charts.bitnami.com
    condition: redis.builtin
  - name: postgresql
    version: 13.2.24
    repository: https://mirror.yandex.ru/helm/charts.bitnami.com
    condition: postgresql.builtin