apiVersion: v2
name: kafka-art
description: Kafka chart
type: application
version: 0.1.0
dependencies:
- name: kafka
  condition: kafka.enabled
  repository: https://mirror.yandex.ru/helm/charts.bitnami.com
  version: 26.8.3
- name: kafdrop
  version: 0.1.0
  condition: kafdrop.enabled
