---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: redis
  namespace: redis
spec:
#  repo: 'https://charts.bitnami.com/bitnami'
  repo: 'https://mirror.yandex.ru/helm/charts.bitnami.com'
  chart: redis
  version: 18.12.1
  targetNamespace: redis
  valuesContent: |-
    global:
      redis:
        password: 'password'
    pdb:
      create: true
    replica:
      replicaCount: 1
