apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system-harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Harbor installation
  sourceRepos:
  - 'https://mirror.yandex.ru/helm/charts.bitnami.com'
  - 'https://helm.goharbor.io'
  - 'https://github.com/BigKAA/youtube'
  destinations:
  - server: https://kubernetes.default.svc
    namespace: 'system-harbor'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
